theme: jekyll-theme-architect
title: Surya Gutta
description: Software Architect | Machine Learning | Statistics | AWS | GCP | Individual Contributor | End-to-End Implementation
show_downloads: false
